### ISSUE TITLE
Why do I bake animation, the car is not running on the path?

### ISSUE THREAD

**Issue by ZhangBin0822** [digicreatures/rigacar#10]
hello，I did an animation of a few cars, the other ones are fine, there is a problem, my bake animation car flies,I rig it once or not.
![QQ图片20190711152639](https://user-images.githubusercontent.com/50355201/61031038-4a451d00-a3f1-11e9-8945-d8e679098b9b.png)
![QQ图片20190711152720](https://user-images.githubusercontent.com/50355201/61031044-4d400d80-a3f1-11e9-8b63-ad2d43c46d5b.png)

**Comment by spoonless** [comment]
Check the ground object has a scale of (1, 1, 1).
Shrinkwrap contraint depends on the scale of the target object.
