### ISSUE TITLE
Baking steering and rotation doesnt work

### ISSUE THREAD

**Issue by Allard888** [digicreatures/rigacar#12]
I have a problem with this addon…

I have the latest version installed for 2.8, and did everything step for step…

But when I press bake steering, i only get 1 green keyframe at the end of the framerange… nothing more… So that doesnt work… also…the rotation of the wheels dont work either when I bake them…

here is the blendfile
https://www.dropbox.com/s/qokteihsr1fc1bk/rigacar%20start%20punt_path.blend?dl=0

**Comment by jammis** [comment]
i have the same problem 🤔🤔

**Comment by Allard888** [comment]
I might found the solution..maybe it helpt for you too...

For me, it went wrong when adding the contraint to the path.. I selected the rig, then added the constraint.. BUt you have to do this

- select path
- shift select rig
- go to pose mode
- just select the rig:root widget (the big one with the arrow)
- add contraint 

this worked for me...hope it helps you too

**Comment by jammis** [comment]
thanks, i try this one 😊😊

**Comment by jammis** [comment]
Hello good day, i just tried your tips, and it works , thanks,
by the way how can move the car fast?

**Comment by Allard888** [comment]
Great, glad it works

If you want the car to go fast... You need to decrease the distance between the keyframes of animated path offset. 

So you animated car movement, by keyframing the offset in the followpath constraint, yes? 

If you go to your dopesheet en view those keyframes... just bring the last keyframe more to the left to increase the speed...and to the right if you want the car to go slower..

**Comment by jammis** [comment]
yes i was able to animate, and all was working fine, but how to animate
fast on long distance?

**Comment by Allard888** [comment]
just set the keyframes first for the right distance...and to speed it up..move the keyframes closer to each other so it takes less time to go from keyframe A to B

**Comment by Finn1510** [comment]
> I might found the solution..maybe it helpt for you too...
> 
> For me, it went wrong when adding the contraint to the path.. I selected the rig, then added the constraint.. BUt you have to do this
> 
> * select path
> * shift select rig
> * go to pose mode
> * just select the rig:root widget (the big one with the arrow)
> * add contraint
> 
> this worked for me...hope it helps you too

Hey, thank you for posting this ! 
I've just the problem that I don't know what you mean with the  rig:root widget (the big one with the arrow)... Can you explain this please ?

**Comment by Finn1510** [comment]
I have another question .Unfortunately my car doesn't moves when I adjust the offset of the path constraint everything works. But after I set the animation and started it with alt a  the car doesn't moves can anyone help me ?

**Comment by makegames-youtube** [comment]
I'm using version 2.80.75, and I'm still having the baking issue.

I have tried the fix mentioned above on a BMW Rigacar mesh, and the Audi from the attached blend file on this thread, but the fix doesn't seem to work on my Blender.

What version of Blender 2.8 are you guys using?

Thank you in advance.

**Comment by jammis** [comment]
im using the latest build, & rig a car is doing fine

**Comment by ckalan123** [comment]
Jammis,
Please explain how you got rigacar to work.  I have tried blender 2.80 and 2.81. As long as I use a straight line the wheels turn. When I use a curve path and bake the rotation of the wheel it does not work. Any tips would be appreciated. 
Thanks,
Craig

**Comment by jammis** [comment]
what i did was after i generate the rig , i add a curve then path, then i
hold shift then left click car rig : root , then on the properties panel
bone constraint properties, its icon is blue bone, there you can change
properties,check follow curve & fixed position, then sleep -Y then up to Z
when you drag the offset the car will start to follow the path

**Comment by Wotisrv** [comment]
Hello guys. I have almost the same problem as you guys. I don't get to insert keys in the timeline even when I follow the steps described here. Everything else is working fine. There is something I do not get.

Blender version 2.80 and 2.81beta.

Any help is appreciated.

**Comment by Wotisrv** [comment]
Now I get this error message when I try to bake car steering or bake wheels rotation.

![Rigacar](https://user-images.githubusercontent.com/48166387/67164217-681f0800-f378-11e9-8030-9bdc71482f6c.jpg)

**Comment by antonvdh** [comment]
Did you solve the error message when trying to bake. I got the same.

**Comment by Q9024** [comment]
Hi, guys. I have solved this problem by using “Bone Constraint Properties” instead of “Object Constraint Properties” when you are adding the “Follow Path”. 
![edfb8490dc06b534cb97b3ec4002b8b](https://user-images.githubusercontent.com/61683406/75966532-7de73100-5f05-11ea-8558-d8f71b4a2e1b.png)

It takes longer to fix the position, but once you done, the addon works well.

Sorry for my English. Hope this could help.

**Comment by shnbwmn** [comment]
@Q9024 Thank you! You're a lifesaver! I was just about to give up on this add-on.

**Comment by spoonless** [comment]
> Now I get this error message when I try to bake car steering or bake wheels rotation.
> 
> ![Rigacar](https://user-images.githubusercontent.com/48166387/67164217-681f0800-f378-11e9-8030-9bdc71482f6c.jpg)

There is a bug in Blender about animation baking. Before baking animation, make sure you have the latest release of this addon and, MOST OF ALL, make sure you have only selected the rig.

**Comment by spoonless** [comment]
Fixed in Rigacar v6.

**Comment by cpg0816** [comment]
Hi, I am hoping I could get some help here. I have Blender 2.83 and Rigacar V6 add-on installed. However, I can't seem to get the car deformation armature/bones correctly even as I followed to the letter the step by step instruction from the documentation.

My problem is there are only four bones (one for each of the four wheels) showing in the model. The bones for the brakewheels doesn't appear. The Transfom panel also is not appearing where you can add bones for the wheels and brakes, etc.

I am sure I have set up the model correctly as shown is the following photos.
Any help is greatly appreciated.

Thanks.

Charlie

![SUV](https://user-images.githubusercontent.com/67248929/85355389-164e0380-b53f-11ea-89ca-24af0aa9dc75.jpg)
![SUV01](https://user-images.githubusercontent.com/67248929/85355395-1948f400-b53f-11ea-98ad-ce00ab2d4bfb.jpg)
![SUV02](https://user-images.githubusercontent.com/67248929/85355400-1a7a2100-b53f-11ea-98ba-87ff0e3f385e.jpg)
![SUV03](https://user-images.githubusercontent.com/67248929/85355407-1bab4e00-b53f-11ea-90b0-81d9a0789500.jpg)
![SUV04](https://user-images.githubusercontent.com/67248929/85355410-1cdc7b00-b53f-11ea-8cf2-d151d4e3b6d9.jpg)
![SUV05](https://user-images.githubusercontent.com/67248929/85355415-1e0da800-b53f-11ea-9632-ff0b349f3e86.jpg)
![SUV06](https://user-images.githubusercontent.com/67248929/85355417-1f3ed500-b53f-11ea-94a7-5455541b38c6.jpg)
![SUV07](https://user-images.githubusercontent.com/67248929/85355420-20700200-b53f-11ea-80fe-9d41ee9e12c6.jpg)
![SUV08](https://user-images.githubusercontent.com/67248929/85355423-21a12f00-b53f-11ea-8845-8545c225655e.jpg)
![SUV09](https://user-images.githubusercontent.com/67248929/85355426-236af280-b53f-11ea-8b6f-4b0f1d93e069.jpg)
![SUV10](https://user-images.githubusercontent.com/67248929/85355427-249c1f80-b53f-11ea-8aa8-7a0c8ccfadb0.jpg)
![SUV11](https://user-images.githubusercontent.com/67248929/85355428-25cd4c80-b53f-11ea-82f5-f6e499059a56.jpg)
![RigAcar Port](https://user-images.githubusercontent.com/67248929/85355439-2ebe1e00-b53f-11ea-9751-facb0179d0df.png)
![RigAcar Port 02](https://user-images.githubusercontent.com/67248929/85355447-34b3ff00-b53f-11ea-8c04-64bb5ee9f065.png)
![RigAcar Port 03](https://user-images.githubusercontent.com/67248929/85355449-367dc280-b53f-11ea-824e-186761d2ed56.png)

**Comment by jammis** [comment]
You can check my video
i hope it can help you
fyi this is on rigacar v5

**Comment by cpg0816** [comment]
Hello,

Thanks for the response. Can you point me to the link where the video is
located?

Thank you very much.

Charlie

**Comment by spoonless** [comment]
Sorry but you miss important things. According to your screenshots, the origin points of your objects are at the wrong position. Each origin point is used by rigacar to indicate where the related bone should be placed in the armature. Check the brakes for instance, their origin point is almost at the center of the world. Also, when you add the armature, you have first to select the objects of your model. This way, you can put has many models in your scene as you want. Rigacar uses only the selected objects to create the base deformation rig.
PS: please do not post any comment on already closds issue. Do not hesitate to create a new one.

**Comment by jammis** [comment]
https://youtu.be/JMTAZ3eadgU

**Comment by cpg0816** [comment]
Many thanks for the response.

Charlie

**Comment by itsnishantsharma** [comment]
> Hi, guys. I have solved this problem by using “Bone Constraint Properties” instead of “Object Constraint Properties” when you are adding the “Follow Path”. ![edfb8490dc06b534cb97b3ec4002b8b](https://user-images.githubusercontent.com/61683406/75966532-7de73100-5f05-11ea-8558-d8f71b4a2e1b.png)
> 
> It takes longer to fix the position, but once you done, the addon works well.
> 
> * only select the rig in object mode
> * go to pose mode, and select the biggest rig
> * go to Bone Constraint Properties, and add “Follow Path”
> * fix position
> * set first and last frame
> * click bake steering and rotation
> 
> Sorry for my English. Hope this could help.

thank you so much bro

**Comment by antonvdh** [comment]
Really thanks for that !
Happy blending
Anton


Op za 12 nov. 2022 09:03 schreef itsnishantsharma ***@***.***

**Comment by antonvdh** [comment]
Would it be possible to also use this add on for a motorcycle rig.

Greetings
***@***.***

**Comment by MAMILO20** [comment]
> I might found the solution..maybe it helpt for you too...
> 
> For me, it went wrong when adding the contraint to the path.. I selected the rig, then added the constraint.. BUt you have to do this
> 
> * select path
> * shift select rig
> * go to pose mode
> * just select the rig:root widget (the big one with the arrow)
> * add contraint
> 
> this worked for me...hope it helps you too

i tried doing it but when i try to bake i cant see the keyframes and the car wont move, pls help

**Comment by MisamotoGames** [comment]
when i click bake wheel rot or bake steering the animation just dissapears what
