### ISSUE TITLE
Addon not properly working on Blender 4.x+

### ISSUE THREAD

**Issue by LucasAlfare** [digicreatures/rigacar#127]
The is basically not working as inteeded.

**Comment by batonchick1** [comment]
Why didn't you read the threads below before creating a new topic? Everything has already been decided there a long time ago

**Comment by LucasAlfare** [comment]
Don't get nervous. I did it to reffer/address my own [pull request](https://github.com/digicreatures/rigacar/pull/128). Anyway, is not a crime, at the end.
