### ISSUE TITLE
Car wheels not rotating when following path.

### ISSUE THREAD

**Issue by timwhois** [digicreatures/rigacar#129]
Hi, 

**Using Blender 4.0.2** and the suggested fixed blendrig file on here - 

Having an issue with the rig, if i move the car along the Y axis wheels appear to move... once i add the constrain to follow a curve and add start and finish keyframes and bake wheel rotation, the keyframes appear on the timeline but when playing the animation, wheels do not appear to be rotating and stay static.... any ideas?

**Comment by LucasAlfare** [comment]
Same

**Comment by batonchick1** [comment]
> Hi,
> 
> **Using Blender 4.0.2** and the suggested fixed blendrig file on here -
> 
> Having an issue with the rig, if i move the car along the Y axis wheels appear to move... once i add the constrain to follow a curve and add start and finish keyframes and bake wheel rotation, the keyframes appear on the timeline but when playing the animation, wheels do not appear to be rotating and stay static.... any ideas?

In this addon, the wheels move in real time only along the Y axis. This is something like a preview. For the wheels to rotate correctly, baking must be done.

**Comment by timwhois** [comment]
Yes, but when I try to bake the wheel rotation, it creates the keyframes but there is no movement?

**Comment by Toxic-Speed** [comment]
> Yes, but when I try to bake the wheel rotation, it creates the keyframes but there is no movement?

same problem bro

**Comment by batonchick1** [comment]
> > Yes, but when I try to bake the wheel rotation, it creates the keyframes but there is no movement?
> 
> same problem bro
@timwhois @Toxic-Speed 
tell me, are you using the corrected version of the addon from post #125? Everything works fine for me in this version.
![image](https://github.com/digicreatures/rigacar/assets/127872529/f1e6fb57-fdc6-432c-a2aa-78cdf022c400)

**Comment by Toxic-Speed** [comment]
yes bro

**Comment by Toxic-Speed** [comment]
![Screenshot (19)](https://github.com/digicreatures/rigacar/assets/155343997/ea22892c-3999-4435-a9e8-20ee5feee25f)

**Comment by timwhois** [comment]
Yes, as mentioned, it creates the keyframes but wheels do not rotate when playing the animation :(

<img width="951" alt="Screenshot 2024-02-01 at 09 29 45" src="https://github.com/digicreatures/rigacar/assets/158100688/dd2a9140-dca3-4d08-896e-0a373a760e74">

<img width="995" alt="Screenshot 2024-02-01 at 09 33 36" src="https://github.com/digicreatures/rigacar/assets/158100688/97c3ec97-408c-44fb-853b-5380b2f19c57">

<img width="482" alt="Screenshot 2024-02-01 at 09 30 45" src="https://github.com/digicreatures/rigacar/assets/158100688/9af3d3f5-6574-4a97-8a67-956da8cfa934">


Maybe issue between Mac and PC? I'm using a Mac if that makes a difference?

**Comment by batonchick1** [comment]
> Yes, as mentioned, it creates the keyframes but wheels do not rotate when playing the animation :(

> Maybe issue between Mac and PC? I'm using a Mac if that makes a difference?
@timwhois @Toxic-Speed 

Are you 100% sure you are using this version from post #125? Visually they have no differences in the addon menu. For correct installation, you need to uninstall the old version of the add-on and then install this one.
[rigacar_fix_from_jiapeiLu.zip](https://github.com/digicreatures/rigacar/files/14125146/rigacar_fix_from_jiapeiLu.zip)

As an example, here is a simple scene that I just made and baked the rotation of the wheels and the steering wheel (blender 4.0.1)
[RigCar_test.zip](https://github.com/digicreatures/rigacar/files/14125164/RigCar_test.zip)

**Comment by Toxic-Speed** [comment]
yup bro I am 200 percent sure and @timwhois I am using pc but the problem is still there its not about mac and pc

**Comment by batonchick1** [comment]
@Toxic-Speed  

Perhaps you are not moving the car itself correctly and the wheels “think” that they are at rest, so the rotation is not baked. For baking to occur, the root must move independently, not being a child of any other object.
For example, if you have tied the root to a empty and move the empty, then the “root” itself is in a resting position, in which case the rotation of the wheels will not be affected.

**Comment by jiapeiLu** [comment]
Hi,
If you can upload the two files. I may help to check the issue.
1. The one before baking wheels animation.
2. The other one baked wheel animation.

To Record and upload a video which show how you processing also help to debug.

**Comment by Toxic-Speed** [comment]
Uploading _ (Unsaved) - Blender 4.0 2024-02-02 08-11-07.mp4…

**Comment by timwhois** [comment]
Hi,

I have had a look at your test file @jiapeiLu and your file seems to work within my blender/addon preferences which must mean its my rig, although i have tried multiple car rigs and they all do the same.

Im interested, maybe im doing things completely wrong and things have changed over time.... within your file i cant see the follow path constraint, so how does it know how to follow the path....? Any possibility you could share a video of how you got the rig to follow the path etc, to see if im doing it differently...?

If you dont have time, totally understand, im still trying to learn but i've done it the same as all the youtube videos i've watched (and used in older blender versions which worked)....

Let me know, thanks! :)

**Comment by timwhois** [comment]
OK!!! I got it, i think I worked it out, thanks to @jiapeiLu !!

@Toxic-Speed I think what I had done wrong was adding the curve constraint under the normal constraints tab.... but actually it should go under Bone Constraints.... 

<img width="279" alt="Screenshot 2024-02-03 at 15 49 07" src="https://github.com/digicreatures/rigacar/assets/158100688/6ea51f80-0ce6-4b3a-842e-d514b932359d">

So this time it worked for me and wheels are now rotating as it follows the path!!! 

Amazing thanks for everyones help!

**Comment by Toxic-Speed** [comment]
Thanks everyone I was also doing the same mistake
