### ISSUE TITLE
Car doens't move...

### ISSUE THREAD

**Issue by Finn1510** [digicreatures/rigacar#13]
I have another question .Unfortunately my car doesn't moves when I adjust the offset of the path constraint everything works. But after I set the animation and started it with alt a  the car doesn't moves can anyone help me ?

**Comment by spoonless** [comment]
Sorry, it seems a general question about how to animate in Blender. Have you already created animation with Blender? I suggest you should take a look at tutorials about that topic. Have you inserted keyframes to animate the offset property?
