### ISSUE TITLE
enabling rig problem

### ISSUE THREAD

**Issue by anandjabuvani** [digicreatures/rigacar#14]
after installing add on from file if i enable rig an error occurs 9[
![924b56b0-f343-4c7c-9e13-ac044dd565e4](https://user-images.githubusercontent.com/54930065/64318424-a97d7300-cfd7-11e9-9425-52ddf0addc99.jpg)
trace back (more recent call last)]

**Comment by spoonless** [comment]
Current version is only for blender 2.8X.
For Blender 2.79 please download 
https://github.com/digicreatures/rigacar/releases/download/v4.0/rigacar-4.0.zip
