### ISSUE TITLE
Moving bones manually not working

### ISSUE THREAD

**Issue by nack8** [digicreatures/rigacar#15]
I had an issue generating the rig properly (Only the main bone would generate) even though my naming convention and origin points are correct so I placed all pones manually. How do I proceed generating the rig after I have done so? I'm not sure what the hierarchy needs to be for this to work. How are the parts parented to the bones?
I've tried dissecting other files but I'm fairly new to Blender so I can't find the proper relationships. Any help would be appreciated thanks!

**Comment by spoonless** [comment]
Could not answer without reviewing the model.

**Comment by spoonless** [comment]
Sorry, could not provide any help without more feedback.
