### ISSUE TITLE
Wheel and steering not working after baking 

### ISSUE THREAD

**Issue by antonvdh** [digicreatures/rigacar#17]
Is it possible to generate the rig without brakes.
I have no brakes to show in the animation so I left them when generating.
When I try to bake the car steering the steering does not work and when bake the wheels for rotation the rotation is not show when playing along the path.
I can see the wheels rotation is recorded in the dopesheet?
Why is the rotation not showing when playing the recorded animation(Blender 2.81)

**Comment by antonvdh** [comment]
OK I did the rigging all over again now with brakes but generate steering or wheel rotation still does not work. I have no idea why I get an error when generating. Now the carrig is useless.
![20200215_101913](https://user-images.githubusercontent.com/1901385/74585482-663f1b80-4fdd-11ea-8484-148398798e55.jpg)

**Comment by jwexplorer** [comment]
Same with me.

No complaints in Blender with the following adjustment in car_rig.py, lines 477-478:
           bpy.ops.object.mode_set(mode='OBJECT')
           self.set_origin(scene)

**Comment by spoonless** [comment]
Fixed in Rigacar v6.0. This is bug of the bake action operator provided by Blender.
Implemented workaround: when you bake animation, additional selected objects are automatically deselected.
