### ISSUE TITLE
Amount of wheels and brakes

### ISSUE THREAD

**Issue by johnwheeler1** [digicreatures/rigacar#18]
Would it be possible to change the amount of wheels and brakes from four to three?

**Comment by spoonless** [comment]
If you mean: having one wheel at the front (or the rear). No you can't. Actually, it would mean a specific rig (especially for the suspension). If you have some skills for rigging in Blender, you can generate the final rig using proxy wheels then try to tweak the rig manually. Probably not the easy way...
