### ISSUE TITLE
Rigacar Add-on doesn't appear despite having downloaded it multiple times

### ISSUE THREAD

**Issue by AlexSenties** [digicreatures/rigacar#19]
I don't know how to solve this problem. I was working in Blender 2.82 and having realized it was for Blender 2.80, I switched to Blender 2.8. Despite that, it still didn't appear after I individually downloaded each file multiple times, even when I searched for rigacar AND refreshed the page. I would really appreciate some help here since this add-on is amazing and I'm anxious to use it when I finally manage to successfully install & enable it. What can I do to fix this?

**Comment by AlexSenties** [comment]
![Captura de Pantalla 2020-03-31 a la(s) 19 40 38](https://user-images.githubusercontent.com/62629188/78090567-b7d21880-7387-11ea-9d09-3b3938ccf63b.png)

![Captura de Pantalla 2020-03-31 a la(s) 19 41 35](https://user-images.githubusercontent.com/62629188/78090574-bbfe3600-7387-11ea-83c6-e12e857b8cc7.png)

![Captura de Pantalla 2020-03-31 a la(s) 19 41 51](https://user-images.githubusercontent.com/62629188/78090579-be609000-7387-11ea-9423-f2081a8061cb.png)

**Comment by Punkerplage** [comment]
It seems like you're trying to install single python files.  Have you tried downloading the file rigacar.v5.0.zip and installing it in Blender?

**Comment by AlexSenties** [comment]
Yes, but it forces me to select one specific file from the folder. I've downloaded all the files on the website, just to make sure.

**Comment by spoonless** [comment]
@Punkerplage is right. Maybe MacOS tricks you by opening the archive after the download (remember me something about that).
First solution: 
* got to the Download folder and zip the rigacar folder.
* try to install the archive
Second solution:
* copy the rigacar folder directly into the Blender addon directory:
    /Users/$USER/Library/Application Support/Blender/2.82/scripts/addons

**Comment by spoonless** [comment]
Sorry, could not provide any more help without feedback. Hope your problem is fixed.
