### ISSUE TITLE
My ground sensors are adding an offset adding a gap between the vehicle and the ground

### ISSUE THREAD

**Issue by karsonhkent** [digicreatures/rigacar#21]

**Comment by spoonless** [comment]
I met this kind of issue once. Check you applied scale for the ground and the model. Blender multiplies the distance of the shrinkwrap contraint (used to stick the sensors to the groun) by the scale of the ground object. So the scale factor must be (1,1,1).

**Comment by mattylonglegs** [comment]
I have also solved this problem by applying the scale to the ground.

**Comment by darknezzgr** [comment]
I have the same problem... when scaling the ground (lets say a plane) and trying to use ground sensor then position of the car is wrong (it goes up, creating an offset)

**Comment by spoonless** [comment]
You simply cannot scale the ground (or you have to apply the scaling). Actually this comes from how certain bone constraints are implemented in Blender.
Generally speaking, rigging or animating models which have a scale different from (1, 1, 1) in Blender can lead to weird effects.
