### ISSUE TITLE
when applying rigacar to follow a path

### ISSUE THREAD

**Issue by SSupremeWolfie** [digicreatures/rigacar#24]
when I try to apply rigacar to follow a path,  it makes my model either extremely small or disappears   
<img width="1920" alt="Screen Shot 2020-06-16 at 3 01 40 AM" src="https://user-images.githubusercontent.com/66999457/84761041-b58e5c00-af7d-11ea-901f-b0df0d2a061b.png">

**Comment by spoonless** [comment]
Have you activated "Curve Radius" in follow path constraint by mistake? This option scales your model (or your bone) according to the radius of the curve.

**Comment by spoonless** [comment]
Sorry, could not provide any more help without feedback. Hope your problem is solved.
