### ISSUE TITLE
Rigacar v6 installed in Blender 2.83

### ISSUE THREAD

**Issue by cpg0816** [digicreatures/rigacar#25]
I have  been trying to figure out with no luck to enable the car deformation rig to my model even if I followed correctly the naming convention suggested. Only 4 bones were created and there seems to be missing bones for the brakes. I am pretty sure I have configured the model and have separate objects for the wheels and brakes yet Rigacar couldn’t detect and setup the rig properly. 

I could not also figure out how to display the deformation panel to add bones for wheels, brakes.
The model I'm working with is a Ford Everest(2017) 3D Model I obtained from 3dcadbrowser

Any help is greatly appreciated.

Thanks,

Charlie

**Comment by spoonless** [comment]
Already answered in https://github.com/digicreatures/rigacar/issues/12
