### ISSUE TITLE
Body roll and pitch

### ISSUE THREAD

**Issue by mattylonglegs** [digicreatures/rigacar#27]
No matter how much I adjust the pitch and roll factor values, I can't get any kind of body motion to animate automatically with the rest of the vehicle. I've tried hand animating to keyframes, but so far my attempts look terrible. 

The rest of the rig seems to be working fine. I'd appreciate any insight. 

working in 2.83. Thank you!

**Comment by spoonless** [comment]
Rigacar is mainly a tool to generate rig for animation. So there is no way to animate automatically the body of your car. Rigacar is not a simulation tool. Good news is you can do whatever you want! Bad news is you have to do it yourself!

I can only encourage you to improve your animation skill.  But maybe the design of the rig does not allow you to do what you want. If you have some feedbacks about how the rig could be improved to make animation easier, please leave a comment below.

**Comment by mattylonglegs** [comment]
I guess my confusion comes from the options for pitch and roll values. What exactly do those values influence? Is the body pitch in the video where you demonstrate the wheel braking widget hand animated?

And I definitely need to improve my animation skills.

**Comment by spoonless** [comment]
About the pitch and roll values: they are influence factors for the wheel dampers. For instance if you put zero for both values, dampers have no effect. Their usage is far from clear without looking at the documentation. Could be useful to have tool tips but it seems not possible to add tooltip on such properties with the Blender API.
In the video about the braking, I simply animate the suspension widget (the yellow arrows above the car) to make the body pitch.

**Comment by spoonless** [comment]
Adding tooltip in Rigacar v6.0. Hope it will help to make things clearer
