### ISSUE TITLE
Is there a way to change the speed of the car?

### ISSUE THREAD

**Issue by stinkhawk** [digicreatures/rigacar#28]
I am trying to make my car slow down and speed up. I just keyframing the offset in Follow Path but it doesnt work very well... is there another way to do this?

**Comment by spoonless** [comment]
If you animate your model using a follow path constraint, nope I know no other way. Use the graph editor to tweak the offset value. If you are not used to the graph editor, take a look at some videos about animation in Blender.

**Comment by spoonless** [comment]
Sorry, could not provide any more help without feedback. Hope you found some info about animation.
