### ISSUE TITLE
Not working on keyframes??

### ISSUE THREAD

**Issue by NumseBacon** [digicreatures/rigacar#33]
So I select "Car Rig" and go to first frame and press I with Offset at 0. Then I go to last frame and press I with offset 1, and nothing happens when I move the timeline

**Comment by spoonless** [comment]
If you are talking about animating your car along a path.
1) The follow path constraint must be on the root widget. Use a bone constraint, not an object constraint on the rig itself.
2) When you manually change the value of the offset of the follow path constraint, the root widget should move along the curve.

This is not related with rigacar. Please check tutorials online about how to use follow path bone constraint.
