### ISSUE TITLE
When adding follow path: Car gets pushed outside the curve

### ISSUE THREAD

**Issue by lotfai** [digicreatures/rigacar#35]
Hello there,

Thank you so much for this amazing free add on. What a great job.

I was wondering why my car gets pushed outside the path when I add the "follow path" function...
The Bones seem to stay at the former position of the car though.

![rig-a-car-follow-path-A](https://user-images.githubusercontent.com/71819780/94129760-0c001600-fe5c-11ea-883f-7d4d0c8c03df.gif)

**Comment by spoonless** [comment]
Check you have added the follow path constraint on the root bone not the armature itself. Also check your model and your armature are at the centre of your scene. Just reset the transformations.
