### ISSUE TITLE
Rigacar 6.0 not installing into Blender 2.83, 2.9 or 2.91

### ISSUE THREAD

**Issue by drinner** [digicreatures/rigacar#40]
Unless this installation follows a different method besides going to the "addons" properties within the preferences menu and simply installing it from file, then I have no idea why this isn't working.  Do I need to actually unzip this zip file?  Most of the time if you want to install an addon, all you need to do is what I described in my first sentence.  When I go through the standard addon install process with this "Rigacar" addon, nothing happens after I do it.  It doesn't appear in the Tools-sidebar next to the outliner or anywhere else.  I don't know what's going wrong here but I'm really bummed about this.  Anybody else experience this issue?

**Comment by WhenLifeHandsYouLemons** [comment]
I don’t get this problem on blender 2.90. Try reinstalling (delete the folder and download it again) the rigacar addon. If the problem still persists, then try to reinstall blender. Hope this helps!

**Comment by drinner** [comment]
WhenLifeHandsYouLemons are you using the most recent, 6.0 version of Rigacar?  Or an earlier version?

**Comment by WhenLifeHandsYouLemons** [comment]
I'm using "rigacar.v6.0"

**Comment by drinner** [comment]
Right... that's what I did.  I just tried to install it on a totally different computer with Blender version 2.83, 2.90 and 2.91 more than once, and it STILL won't work...  I don't feel the need to reinstall Blender even though I really want to use this Addon... if it's not working on either computer.  I literally have no idea what's causing it, but I'm not convinced that it's Blender.

**Comment by WhenLifeHandsYouLemons** [comment]
Hmmm...
Do you see the addon in the addon panel in preferences once you try to install it?

**Comment by drinner** [comment]
Yeah!  That's the crazy part!  I see the addon and I click to install it and everything seems like it's going to work... but then the addon itself never appears on the side of the outliner along with all the other addons.  The other annoying thing is that Rigacar addon appears in the "Filter Addon" panel in the "Workspace" section of the "Tools" tab that's on the side of the Outliner, too! 
 I really want to use this addon with the really incredible TRANSPORTATION addon.  That's where I found out about this particular addon.

**Comment by drinner** [comment]
![Rigacar not working](https://user-images.githubusercontent.com/54718333/105283416-0b5f5e00-5b76-11eb-8814-43435ea0da14.png)

**Comment by WhenLifeHandsYouLemons** [comment]
Try ticking that button, it might just work. 😁

**Comment by WhenLifeHandsYouLemons** [comment]
I've figured out your problem!

1. Enable the addon in preferences.
2. Once you've done that, import a car into the scene.
3. Select the car and click "Shift + A" to add.
4. Go to "Armature" and click on "Car (deformation rig)".
5. Now the tab should have appeared in the panel at the side!

Hope this works for you too!

**Comment by WhenLifeHandsYouLemons** [comment]
# Step 1
![image](https://user-images.githubusercontent.com/54261970/105286811-f9bb9c00-5bf1-11eb-8ec9-ef4e6fe769b6.png)

# Step 2
![image](https://user-images.githubusercontent.com/54261970/105286870-148e1080-5bf2-11eb-81e0-b2751489db65.png)

# Step 3
![image](https://user-images.githubusercontent.com/54261970/105286915-296aa400-5bf2-11eb-961d-028715b64845.png)

Do step 3 after you've oriented the car and adjusted the armature to the car. If you want, here's the video on how to do adjust the armature correctly. 👇
https://www.youtube.com/watch?v=D3XQxA_-TzY&list=PLH_mmrv8SfPFiEj93RJt3sBvHCnipI9qK

**Comment by drinner** [comment]
WhenLifeHandsYouLemons  GOD BLESS YOU BROTHA!!!!  Thank you for your help!!!

**Comment by BlenderDefender** [comment]
@drinner Now that it's fixed, you should close this issue.

**Comment by WhenLifeHandsYouLemons** [comment]
I can't close the issue, it has to be done by the one who opened it I think.

**Comment by BlenderDefender** [comment]
@WhenLifeHandsYouLemons I know, only @digicreatures and @drinner can close this issue, that's why I mentioned @drinner

**Comment by spoonless** [comment]
@WhenLifeHandsYouLemons thanks for your help
