### ISSUE TITLE
Rigacar crashing Blender 2.90.1 when I tried Generate

### ISSUE THREAD

**Issue by jackomj92** [digicreatures/rigacar#41]
Hi there, I have a problem with Generate rigg. When I press Generate button then Blender crash and close to Desktop. I have installed v6 version. How I can fix it ? Thanks :)

**Comment by WhenLifeHandsYouLemons** [comment]
How powerful is your computer? It may be because your computer can’t handle it?

**Comment by jackomj92** [comment]
This is my Lenovo Legion Y520 specification: 

Intel Core i5 (7th Gen) 7300HQ / 2.5 GHz
8 GB RAM 
NVIDIA GeForce GTX 1050

**Comment by jackomj92** [comment]
Ok I solved problem :) I have update Blender to new version and I works fine ;)
