### ISSUE TITLE
just not working at all

### ISSUE THREAD

**Issue by CGlearning** [digicreatures/rigacar#44]
hello! i love the idea of your product, however sadly i have been unable to use it. i have watched your full video series and when i try and add the rig after setting up the naming conventions it goes completely wild and no where near the parts and sometimes it stretches my model massively. I would really appreciate any help you could give as i think this product is awesome.

**Comment by CGlearning** [comment]
if it helps i can upload the .blend file

**Comment by spoonless** [comment]
Yes please, share your file

**Comment by CGlearning** [comment]
hey! thanks so much for responding! i am relatively new to github and i don't see how to upload my .blend file when i try and drag and drop it says file type not excepted. how should i upload the file? 
thanks!

**Comment by carcarforevar** [comment]
Hi! you can try uploading it on a google drive and send a link in here

**Comment by CGlearning** [comment]
https://drive.google.com/file/d/1awaDpR7REWcw4h5ha9pagsaUOagwWsKw/view?usp=sharing

**Comment by spoonless** [comment]
You missed something really important.
You have to set correctly the origin point for each part of your model. This way, Rigacar knows where to put the bones.
For instance, the origin point for the wheel should be at the centre of the wheel.
http://digicreatures.net/articles/rigacar.html#check-origins

**Comment by CGlearning** [comment]
oh i see what your saying, i have reset the origin to the center of each of their respective geometry's however it still is generating the rig 4 or 5 car lengths away. What am i missing?

**Comment by CGlearning** [comment]
never mind i figured it out!! thank you so much for taking the time to help me out!!!! i think this is an incredible asset and thank you so much for making it available!!

**Comment by spoonless** [comment]
no problem.
Drive safely.

**Comment by CGlearning** [comment]
thanks again!

**Comment by agniveshsp** [comment]
> never mind i figured it out!! thank you so much for taking the time to help me out!!!! i think this is an incredible asset and thank you so much for making it available!!

Can you share the solution?
