### ISSUE TITLE
Rig creating offset and upside down

### ISSUE THREAD

**Issue by Fibly** [digicreatures/rigacar#46]
I followed all the proper steps on the site and tried again watching the video, can't figure out what's causing it
![Screenshot 2021-04-15 115447](https://user-images.githubusercontent.com/82604817/114908176-71f4c080-9de1-11eb-9019-d81a9bddd1aa.jpg)

**Comment by spoonless** [comment]
Your model is probably not aligned as rigacar expects.
The model should be aligned along the -Y axis. To say things differently, in the front view, you should see the front of your model.
Remove the rig, rotate your model and you should apply the rotation.

**Comment by Fibly** [comment]
Ah it works perfectly now thank you!
