### ISSUE TITLE
Does anybody know why after I bake wheel rotation when I activate motion blur messes up the tire rotation?

### ISSUE THREAD

**Issue by shadi113344** [digicreatures/rigacar#48]
I can't figure out why when I bake wheel rotation and render with activated motion blur the car doesn't seem to rotate on over the center while without it everything is working fine. also this issue doesn't appear in Realtime rendering only in the final rendered image.

I'm using cycles however when I tried it on Eevee this issue doesn't exist.

Any ideas about this issue ??

![1](https://user-images.githubusercontent.com/80112723/118359445-d1322600-b583-11eb-9625-3e8bb166c3f2.PNG)
![2](https://user-images.githubusercontent.com/80112723/118359448-d2635300-b583-11eb-9797-f9302f2e8c31.PNG)

**Comment by Pixinside** [comment]
Hello, I have the same issue with blender 3.1. Wheels are bouncing when motion blur is set.

**Comment by spoonless** [comment]
When activated, motion blur depends on the position of the origin point. So the origin of the wheel must be at the center of the wheel.
You must pay extra attention before rigging your model to set correctly the origin points.
