### ISSUE TITLE
instalation issues

### ISSUE THREAD

**Issue by manny2121** [digicreatures/rigacar#49]

**Comment by manny2121** [comment]
i installed in on blender 2.9 but rig is not showing up armature

**Comment by sarpergin12** [comment]
Because then "Rig A Car" add-on isn't compatible with Blender 2.9

**Comment by spoonless** [comment]
@sarpergin12 Rigacar is compatible with Blender2.9x :)
@manny2121 As it works perfectly for me with Blender 2.93.5 on Linux, can you describe more precisely your issue. or even post images if it could help to understand the problem.
