### ISSUE TITLE
Unable to select any part of the rig

### ISSUE THREAD

**Issue by Merlyn666** [digicreatures/rigacar#57]
Unable to select any part of the rig after it is generated. Try moving the 'drift' control while in pose mode, no joy. Blender 3.0 Rigacar v7   .blend file is attached.   carnoirfilms@gmail.com
[Collision003.zip](https://github.com/digicreatures/rigacar/files/7768115/Collision003.zip)

**Comment by spoonless** [comment]
In the object type visibility, you have accidentally marked armature as unselectable.

![screenshot](https://user-images.githubusercontent.com/1173511/151878371-86bf4d7e-39d4-4c98-ba1d-151b7fb7d92c.png)

Just enable it again.
