### ISSUE TITLE
Why do my wheels rotate without baking animations?

### ISSUE THREAD

**Issue by Techno-Sachin** [digicreatures/rigacar#6]
This is actually not an issue. But is it a bug? This happened for me:
I was seeing video tutorials and installing rigs. Everything successful.  I baked steering animations. It worked.  But i did not bake wheels rotation. But still the wheels rotated perfectly. No problems in that animation.

I tried baking the wheel rotation for the first time. It did. But the rotation was over exaggerated. Like per frame-2-5 rotations... like that.

David, is it normal sir? Or should I change anything.

Thank u so much for having this rigacar addon free! I came to rigacar after watching that other video.( Blender Car Rig  - Cliff demo, etc.)

**Comment by spoonless** [comment]
Check if the property "Wheels on Y axis" is activated. Please set this property to 0.
More about it in the documentation :
http://digicreatures.net/articles/rigacar.html#check-the-spinning-of-the-wheels
