### ISSUE TITLE
Bake car steering and rotation not working on 3.1

### ISSUE THREAD

**Issue by Alemandarino** [digicreatures/rigacar#63]
Bake car steering and rotation are not working on new version 3.1 of blender,

Python: Traceback (most recent call last):
  File "C:\Users\Start\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rigacar\bake_operators.py", line 163, in invoke
    self.frame_start, self.frame_end = action.frame_range
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy_types.py", line 778, in __setattr__
    return setattr(properties, attr, value)
TypeError: bpy_struct: item.attr = val: ANIM_OT_car_steering_bake.frame_start expected an int type, not float

location: <unknown location>:-1

Any solution? Thx

**Comment by gco360** [comment]
im using blender version 3.1 and rigcar v7 and i get the same error
![image](https://user-images.githubusercontent.com/31587917/158622185-016ab2f5-3065-4eb1-972a-0f014cf9ecd6.png)

**Comment by gridsquat** [comment]
I changed my copy of the code around line 163 in the bake_operators.py file to look like this and it seemed to fix the problem:-

#        self.frame_start, self.frame_end = int(action.frame_range)
        self.frame_start = int(action.frame_range[0])
        self.frame_end = int(action.frame_range[1])

Sorry, I am new to GitHub so don't know how to properly submit this as a code change.....

**Comment by gridsquat** [comment]
I changed my copy of the code around line 163 in the bake_operators.py file to look like this and it seemed to fix the problem:-

        self.frame_start, self.frame_end = int(action.frame_range)

to

        self.frame_start = int(action.frame_range[0])
        self.frame_end = int(action.frame_range[1])

Sorry, I am new to GitHub so don't know how to properly submit a code change...

**Comment by gco360** [comment]
> I changed my copy of the code around line 163 in the bake_operators.py file to look like this and it seemed to fix the problem:-
> 
> ```
>     self.frame_start, self.frame_end = int(action.frame_range)
> ```
> 
> to
> 
> ```
>     self.frame_start = int(action.frame_range[0])
>     self.frame_end = int(action.frame_range[1])
> ```
> 
> Sorry, I am new to GitHub so don't know how to properly submit a code change...

is that the only change needed or ?

**Comment by gco360** [comment]
please note this is happening because the start frame and end frame are set to zero
after changing the frame numbers it worked

![image](https://user-images.githubusercontent.com/31587917/159129980-6649f3ad-1034-446d-b87b-d90e6e85e1ed.png)

**Comment by spoonless** [comment]
rigacar v7.1 is out to fix this issue.
thanks guys for reporting it.

**Comment by BRO408** [comment]
> Bake car steering and rotation are not working on new version 3.1 of blender,
> 
> Python: Traceback (most recent call last): File "C:\Users\Start\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rigacar\bake_operators.py", line 163, in invoke self.frame_start, self.frame_end = action.frame_range File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy_types.py", line 778, in **setattr** return setattr(properties, attr, value) TypeError: bpy_struct: item.attr = val: ANIM_OT_car_steering_bake.frame_start expected an int type, not float
> 
> location: :-1
> 
> Any solution? Thx

Im also stuck by this problem i thought it  was my mistake but I did it properly but still its not working......
