### ISSUE TITLE
Armature only creates root bone

### ISSUE THREAD

**Issue by PatriotTrav** [digicreatures/rigacar#64]
Adding armature only adds the Body bone. Everything is named as per the naming convention of the video tutorial on Youtube, Scale is applied properly, and the tires are sitting on top of the world grid. When I add the Armature, moving the delta transforms moves the wheels and brakes but there are no bones. When I generate the rig, it only creates the Root, Drift and the top Suspension widgets in the first two layers. I am using Blender 3.1 with the Rigacar v7. All objects are in the same collection. Nothing is parented. All objects are facing the -Y direction. All transforms are applied and object origins are all set to world origin.

**Comment by PatriotTrav** [comment]
![Screenshot 2022-03-18 225612](https://user-images.githubusercontent.com/70449405/159109586-d4b635fb-9bb1-442e-b941-99e670156056.jpg)

**Comment by PatriotTrav** [comment]
![Screenshot 2022-03-18 225740](https://user-images.githubusercontent.com/70449405/159109598-a8b27fc3-df2a-4e7b-96e4-eef53269a183.jpg)

**Comment by PatriotTrav** [comment]
Never mind all that. I guess you can't have anything selected while you are adding the Armature. It seems to work fine when you unselect everything.

**Comment by gridsquat** [comment]
@PatriotTrav My understanding with the object names is that as well as the .bk.r style of suffix they must also have a common prefix. Your body is prefixed BodyFrame but the other objects are prefixed BrakeDisc_WheelBrake and Tire_Wheel. The following setup worked fine for me, my truck does not have visible brakes.
![image](https://user-images.githubusercontent.com/101891663/159110716-ef994c82-4ace-4bc6-b00e-8f0cee25f98b.png)

**Comment by PatriotTrav** [comment]
I tried that as well, after I posted issue. It didn't fix the issue, so I just added the armature without anything selected and manually located all the bones. it worked out great, and it didn't really take that long. Then i manually parented all objects to the rig, which kinda worked out better because I could keep all objects separated. Thank you for responding so quick.

**Comment by PatriotTrav** [comment]
![Screenshot 2022-03-19 105809](https://user-images.githubusercontent.com/70449405/159132864-648c3260-a717-48c8-a081-12f5bc30def3.jpg)
As you can see I have many different collections now rather than joining all the parts into one object. Better for what I want to do.
