### ISSUE TITLE
"Upgrade to 2.8x required" error while on the latest blender 2.80.72

### ISSUE THREAD

**Issue by 3rdhope** [digicreatures/rigacar#7]
i'm getting error in the title while trying to enable the addon.

**Comment by spoonless** [comment]
There is two versions of the addon: on for Blender 2.7x and one for Blender 2.80 beta.
It seems you tried to install the one compatible with 2.7x in Blender 2.80 beta. Please take care to download and install the correct one.
I have just released a new version for Blender 2.80 beta, please install it with the latest build of Blender 2.80

**Comment by 3rdhope** [comment]
Perfect. Thanks
