### ISSUE TITLE
Rigacar works ok until I clear the baked wheel info

### ISSUE THREAD

**Issue by sross401** [digicreatures/rigacar#78]
Rigacar does fine, I add the follow path bone constraint, bake the steering and the rotation, okay so far.

![Captur11e](https://user-images.githubusercontent.com/111643986/185747622-db8be2e6-e6aa-4d0b-8a0c-64efb260cd3b.JPG)

However if I clear the baked animation and make an adjustment to the path, like change the animation from 650 to 1000 frames, I can add the follow path constraint....no problem so far...but when I rebake the steering and the rotation-
this happens:
![Captu22233re](https://user-images.githubusercontent.com/111643986/185747810-c76e7966-805b-44e9-8ec4-ca29a594ed7c.JPG)

 and it happens every time. Notice how the front wheels and fenders have flipped on their axes.

Edit: Hey I thought you might want the Blender version and the Rigacar version so I double checked it and was using Blender 3.0 with your 7.1. So I ran the scenario again on 3.1 and it didn't happen again!

 My bad! Well maybe someone can learn from my mistake.

Thanks for the add-on  it works pretty good.

**Comment by spoonless** [comment]
Thank you for your report anyway because I thought 7.1 is backward compatible (but you have proven it is not).
