### ISSUE TITLE
Not working with inclined wheel

### ISSUE THREAD

**Issue by SamL0rd** [digicreatures/rigacar#80]
Hi !
I use the add on on my car but I have an issue: my wheel is inclined (like a tune drift car) and the rotation is not aligned ( as you can see in the video just below. 
Is there a way to make this " normal " ?
Thanks for your support.

https://user-images.githubusercontent.com/112341735/187087469-66b38797-8ef8-4219-abf9-59250ba3af44.mp4

**Comment by spoonless** [comment]
currently cambered wheels are not supported. I suspect it could be possible to camber them after the rig generation by tweaking the rig (but it needs some knowledge of rigging in blender).
I am not 100% sure it will work.
related to #22
