### ISSUE TITLE
Rigicar 7.1 - Baking steering wheel and wheels rotation error. location: <unknown location>:-1

### ISSUE THREAD

**Issue by samoxinvik** [digicreatures/rigacar#81]
Hi! I recorded a short video.

https://youtu.be/r2MC742JETU

Blender 3.1.2 (Blender Octane  addon)
Rigicar 7.1

When I bake the car steering I get an error message:

```
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rigacar\bake_operators.py", line 145, in invoke
    class BakingOperator(object):
  File "C:\Program Files\BlenderOctane\3.1\scripts\modules\bpy_types.py", line 778, in __setattr__
    return setattr(properties, attr, value)
TypeError: bpy_struct: item.attr = val: ANIM_OT_car_steering_bake.frame_start expected an int type, not float

location: <unknown location>:-1
```

When I bake the wheel rotation I get an error message:

```
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rigacar\bake_operators.py", line 145, in invoke
    class BakingOperator(object):
  File "C:\Program Files\BlenderOctane\3.1\scripts\modules\bpy_types.py", line 778, in __setattr__
    return setattr(properties, attr, value)
TypeError: bpy_struct: item.attr = val: ANIM_OT_car_wheels_rotation_bake.frame_start expected an int type, not float

location: <unknown location>:-1
```

But if I change the options in the pop-up menu, the bake works. But how do I get rid of the error?
Thank you.

**Comment by samoxinvik** [comment]
It seems that the error is left over from the previous version. I deleted the __pycache__ folder with the cache in C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rigacar and now everything works fine.

**Comment by samoxinvik** [comment]
It seems that the error is left over from the previous version. I deleted the __pycache__ folder with the cache in C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rigacar and now everything works fine.

**Comment by iranaahsanali** [comment]
I'm still facing the same issue, I have tried clearing the cache. Still not working for me.
