### ISSUE TITLE
The position of the bones is incorrect

### ISSUE THREAD

**Issue by Marcenary** [digicreatures/rigacar#91]
I did everything on the video instructions, but the dice are not added correctly.

![1](https://user-images.githubusercontent.com/62656941/205090567-abd1da68-760f-4f37-ba63-4a47b419c556.png)
![2](https://user-images.githubusercontent.com/62656941/205090579-52349cd5-4b6f-4d90-8df0-b400b618199c.png)

**Comment by spoonless** [comment]
You have to align your model along the Y-axis. In your example, it is aligned along the X-axis.
As a hint: the front of your model will be aligned with the front view
