### ISSUE TITLE
addon not in sidebar panel

### ISSUE THREAD

**Issue by noconelol** [digicreatures/rigacar#94]
for some reason the addon wont appear in the sidebar i already re added the addon 
![image_2022-12-28_020457584](https://user-images.githubusercontent.com/121513589/209705378-bcea34cf-a6f9-4dbb-abe8-809680e4f5c3.png)
![image](https://user-images.githubusercontent.com/121513589/209705411-dd57ed81-2d84-4be4-8e1e-a8b24d476994.png)

**Comment by Time-II** [comment]
It should only appear in the sidebar if you have selected the rig first.
